
// constants.ts

import { Dialect, Language, StudentGoal, Subject, DifficultyLevel, LibraryItemType } from './types';

export const LANGUAGES = [Language.EN, Language.VI, Language.ZH, Language.FR];

export const STUDENT_GOALS = [StudentGoal.GOOD, StudentGoal.EXCELLENT, StudentGoal.OUTSTANDING];

export const GRADES = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

export const SUBJECTS = [
    Subject.MATH,
    Subject.LITERATURE,
    Subject.PHYSICS,
    Subject.CHEMISTRY,
    Subject.BIOLOGY,
    Subject.HISTORY,
    Subject.GEOGRAPHY,
    Subject.ENGLISH,
    Subject.TECHNOLOGY,
    Subject.CIVIC_EDUCATION,
    Subject.INFORMATICS,
    Subject.NATURAL_SCIENCES,
];

export const DIFFICULTY_LEVELS = [
    DifficultyLevel.RECOGNITION,
    DifficultyLevel.COMPREHENSION,
    DifficultyLevel.APPLICATION
];

export const TEXTBOOKS = [
    'none',
    'canh_dieu',
    'chan_troi_sang_tao',
    'ket_noi_tri_thuc',
    'other',
];

export const STORAGE_LIMIT_BYTES = 1 * 1024 * 1024; // 1MB

export const LOCALIZATION_STRINGS: { [key in Language]: { [key: string]: string } } = {
  [Language.EN]: {
    slogan: 'Unlocking knowledge, shaping the future.',
    im_a: "I'm a...",
    student: 'Student',
    teacher: 'Teacher',
    select_goal: 'Select Your Goal',
    good_student: 'Good Student',
    excellent_student: 'Excellent Student',
    outstanding_student: 'Outstanding Student',
    summarize: 'Summarize',
    summarizer: 'Summarizer',
    exam_generator: 'Exam Generator',
    ai_assistant: 'AI Assistant',
    translator: 'Translator',
    slide_generator: 'Slide Generator',
    learning_path: 'Learning Path',
    question_analysis: 'Question Analysis',
    upload_file: 'Upload File',
    file_placeholder: 'Upload a file (PDF, image, audio, video)',
    choose_file: 'Choose File',
    no_file_chosen: 'No file chosen',
    generating: 'Generating...',
    summary_placeholder: 'Your generated summary, mind map, and flashcards will appear here.',
    mind_map: 'Mind Map',
    flashcards: 'Flashcards',
    source_language: 'Source Language',
    target_language: 'Target Language',
    source_text_placeholder: 'Enter text to translate...',
    copy_text: 'Copy',
    copied: 'Copied!',
    copy_as_text: 'Copy as Text',
    copy_for_word: 'Copy for Word',
    converting: 'Converting...',
    swap_languages: 'Swap Languages',
    translate_button: 'Translate',
    presentation_topic: 'Presentation Topic',
    topic_placeholder: 'e.g., "The History of AI"',
    upload_template: 'Upload Template (Optional)',
    generate_slides: 'Generate Slides',
    slide_placeholder: 'Your generated slide content will appear here.',
    grade: 'Grade',
    subject: 'Subject',
    generate_plan: 'Generate Plan',
    completed: 'Completed',
    current_lesson: 'Current Lesson',
    locked: 'Locked',
    plan_placeholder: 'Generate a learning plan to get started.',
    lesson_placeholder: 'Select a lesson to view its content.',
    mark_complete: "Mark as Complete & Next",
    exam_topic: 'Exam Topic',
    multiple_choice: 'Multiple Choice',
    essay: 'Essay',
    generate_exam: 'Generate Exam',
    exam_placeholder: 'Your generated exam questions will appear here.',
    send_message: 'Send',
    teacher_chatbot_greeting: 'Hello! As your creative AI assistant, I\'m here to help brainstorm ideas for your lessons. What\'s on your mind today?',
    teacher_chatbot_placeholder: 'How can I help with lesson planning or creative ideas today?',
    attach_file: 'Attach File',
    file_attached: 'File attached:',
    remove_file: 'Remove file',
    start_recording: 'Start Recording',
    stop_recording: 'Stop Recording',
    voice_unsupported: 'Voice input is not supported by your browser.',
    select_dialect: 'Select Dialect',
    north: 'North',
    central: 'Central',
    south: 'South',
    textbook: 'Textbook',
    upload_matrix: 'Upload Matrix',
    manual_textbook_placeholder: 'Enter textbook name...',
    question_analysis_title: 'Similar Exercise Generator',
    generate_similar_exercises: 'Generate Similar Exercises',
    upload_question_file: 'Upload a question file (image, PDF)',
    similar_exercises_placeholder: 'Your generated similar exercises will appear here.',
    analysis_of_original_question: 'Analysis of the Original Question',
    similar_practice_exercises: 'Similar Practice Exercises',
    read_aloud: 'Read Aloud',
    exam_duration: 'Exam Duration (minutes)',
    num_multiple_choice: 'Total Multiple Choice Qs',
    num_essay: 'Essay Qs by Difficulty',
    difficulty_level: 'Difficulty Level',
    recognition: 'Recognition',
    comprehension: 'Comprehension',
    application: 'Application',
    mc_difficulty_breakdown: 'MC Qs by Difficulty',
    mc_sum_error: 'Sum of MC counts must equal total.',
    review_topic: 'Review Topic',
    generate_review_exercises: 'Generate Exercises',
    review_placeholder: 'Your generated review exercises will appear here.',
    go_home: 'Go Home',
    library: 'Library',
    documents: 'Documents',
    save_to_library: 'Save to Library',
    save_to_documents: 'Save to Documents',
    saved: 'Saved!',
    library_empty: 'Your library is empty. Save generated content to see it here.',
    documents_empty: 'You have no saved documents. Save generated content to see it here.',
    delete: 'Delete',
    view: 'View',
    close: 'Close',
    confirm_delete_title: 'Confirm Deletion',
    confirm_delete_message: 'Are you sure you want to delete this item?',
    storage_full: 'Storage is full. Please delete some items to save new content.',
    storage_usage: 'Storage Usage',
    item_name_placeholder: 'Enter a name for this item...',
    save: 'Save',
    zoom_in: 'Zoom In',
    zoom_out: 'Zoom Out',
    reset_zoom: 'Reset Zoom',
    specialized_review: 'Specialized Review',
    numbers: 'Numbers & Algebra',
    geometry: 'Geometry',
    both: 'Both',
    sub_subjects: 'Sub-subjects',
    none: 'None',
    canh_dieu: 'Cánh diều',
    chan_troi_sang_tao: 'Chân trời sáng tạo',
    ket_noi_tri_thuc: 'Kết nối tri thức với cuộc sống',
    other: 'Other (manual input)',
    image_generation_error: 'Image generation failed',
    [Subject.MATH]: 'Math',
    [Subject.LITERATURE]: 'Literature',
    [Subject.PHYSICS]: 'Physics',
    [Subject.CHEMISTRY]: 'Chemistry',
    [Subject.BIOLOGY]: 'Biology',
    [Subject.HISTORY]: 'History',
    [Subject.GEOGRAPHY]: 'Geography',
    [Subject.ENGLISH]: 'English',
    [Subject.TECHNOLOGY]: 'Technology',
    [Subject.CIVIC_EDUCATION]: 'Civic Education',
    [Subject.INFORMATICS]: 'Informatics',
    [Subject.NATURAL_SCIENCES]: 'Natural Sciences',
    [LibraryItemType.SUMMARY]: 'Summary',
    [LibraryItemType.EXAM]: 'Exam',
    [LibraryItemType.REVIEW_EXERCISES]: 'Review Exercises',
    [LibraryItemType.SIMILAR_EXERCISES]: 'Similar Exercises',
  },
  [Language.VI]: {
    slogan: 'Khai mở tri thức, định hình tương lai.',
    im_a: 'Tôi là...',
    student: 'Học sinh',
    teacher: 'Giáo viên',
    select_goal: 'Chọn Mục tiêu của bạn',
    good_student: 'Học sinh Khá',
    excellent_student: 'Học sinh Giỏi',
    outstanding_student: 'Học sinh Xuất sắc',
    summarize: 'Tóm tắt',
    summarizer: 'Trình tóm tắt',
    exam_generator: 'Tạo Đề thi',
    ai_assistant: 'Trợ lý AI',
    translator: 'Dịch thuật',
    slide_generator: 'Tạo Slide',
    learning_path: 'Lộ trình học tập',
    question_analysis: 'Phân tích Câu hỏi',
    upload_file: 'Tải tệp lên',
    file_placeholder: 'Tải lên tệp (PDF, ảnh, âm thanh, video)',
    choose_file: 'Chọn tệp',
    no_file_chosen: 'Chưa chọn tệp nào',
    generating: 'Đang tạo...',
    summary_placeholder: 'Bản tóm tắt, sơ đồ tư duy và flashcard của bạn sẽ xuất hiện ở đây.',
    mind_map: 'Sơ đồ tư duy',
    flashcards: 'Thẻ ghi nhớ',
    source_language: 'Ngôn ngữ nguồn',
    target_language: 'Ngôn ngữ đích',
    source_text_placeholder: 'Nhập văn bản cần dịch...',
    copy_text: 'Sao chép',
    copied: 'Đã sao chép!',
    copy_as_text: 'Sao chép dạng Chữ',
    copy_for_word: 'Sao chép cho Word',
    converting: 'Đang chuyển đổi...',
    swap_languages: 'Hoán đổi ngôn ngữ',
    translate_button: 'Dịch',
    presentation_topic: 'Chủ đề bài thuyết trình',
    topic_placeholder: 'ví dụ: "Lịch sử của AI"',
    upload_template: 'Tải lên mẫu (Tùy chọn)',
    generate_slides: 'Tạo Slide',
    slide_placeholder: 'Nội dung slide được tạo của bạn sẽ xuất hiện ở đây.',
    grade: 'Lớp',
    subject: 'Môn học',
    generate_plan: 'Tạo kế hoạch',
    completed: 'Đã hoàn thành',
    current_lesson: 'Bài học hiện tại',
    locked: 'Đã khóa',
    plan_placeholder: 'Tạo một kế hoạch học tập để bắt đầu.',
    lesson_placeholder: 'Chọn một bài học để xem nội dung.',
    mark_complete: "Đánh dấu Hoàn thành & Tiếp theo",
    exam_topic: 'Chủ đề bài kiểm tra',
    multiple_choice: 'Trắc nghiệm',
    essay: 'Tự luận',
    generate_exam: 'Tạo Đề thi',
    exam_placeholder: 'Câu hỏi thi được tạo của bạn sẽ xuất hiện ở đây.',
    send_message: 'Gửi',
    teacher_chatbot_greeting: 'Xin chào! Với vai trò là trợ lý AI sáng tạo của bạn, tôi ở đây để giúp bạn lên ý tưởng cho các bài giảng. Hôm nay bạn đang nghĩ gì?',
    teacher_chatbot_placeholder: 'Tôi có thể giúp gì cho việc lên kế hoạch bài giảng hoặc ý tưởng sáng tạo của bạn hôm nay?',
    attach_file: 'Đính kèm tệp',
    file_attached: 'Tệp đính kèm:',
    remove_file: 'Xóa tệp',
    start_recording: 'Bắt đầu ghi âm',
    stop_recording: 'Dừng ghi âm',
    voice_unsupported: 'Trình duyệt của bạn không hỗ trợ nhập liệu bằng giọng nói.',
    select_dialect: 'Chọn vùng miền',
    north: 'Bắc',
    central: 'Trung',
    south: 'Nam',
    textbook: 'Sách giáo khoa',
    upload_matrix: 'Tải lên ma trận',
    manual_textbook_placeholder: 'Nhập tên sách giáo khoa...',
    question_analysis_title: 'Trình tạo Bài tập Tương tự',
    generate_similar_exercises: 'Tạo bài tập tương tự',
    upload_question_file: 'Tải lên tệp câu hỏi (ảnh, PDF)',
    similar_exercises_placeholder: 'Các bài tập tương tự được tạo sẽ xuất hiện ở đây.',
    analysis_of_original_question: 'Phân tích câu hỏi gốc',
    similar_practice_exercises: 'Các bài tập tương tự',
    read_aloud: 'Đọc to',
    exam_duration: 'Thời gian (phút)',
    num_multiple_choice: 'Tổng số câu TN',
    num_essay: 'Số câu TL theo độ khó',
    difficulty_level: 'Mức độ khó',
    recognition: 'Nhận biết',
    comprehension: 'Thông hiểu',
    application: 'Vận dụng',
    mc_difficulty_breakdown: 'Số câu TN theo độ khó',
    mc_sum_error: 'Tổng số câu theo độ khó phải bằng tổng số câu TN.',
    review_topic: 'Chủ đề ôn tập',
    generate_review_exercises: 'Tạo bài tập',
    review_placeholder: 'Bài tập ôn tập của bạn sẽ xuất hiện ở đây.',
    go_home: 'Về trang chủ',
    library: 'Thư viện',
    documents: 'Tài liệu',
    save_to_library: 'Lưu vào Thư viện',
    save_to_documents: 'Lưu vào Tài liệu',
    saved: 'Đã lưu!',
    library_empty: 'Thư viện của bạn trống. Lưu nội dung đã tạo để xem tại đây.',
    documents_empty: 'Bạn chưa có tài liệu nào. Lưu nội dung đã tạo để xem tại đây.',
    delete: 'Xóa',
    view: 'Xem',
    close: 'Đóng',
    confirm_delete_title: 'Xác nhận Xóa',
    confirm_delete_message: 'Bạn có chắc chắn muốn xóa mục này không?',
    storage_full: 'Bộ nhớ đã đầy. Vui lòng xóa bớt các mục để lưu nội dung mới.',
    storage_usage: 'Dung lượng lưu trữ',
    item_name_placeholder: 'Nhập tên cho mục này...',
    save: 'Lưu',
    zoom_in: 'Phóng to',
    zoom_out: 'Thu nhỏ',
    reset_zoom: 'Đặt lại',
    specialized_review: 'Ôn tập chuyên đề',
    numbers: 'Số học',
    geometry: 'Hình học',
    both: 'Cả hai',
    sub_subjects: 'Các môn thành phần',
    none: 'Không',
    canh_dieu: 'Cánh diều',
    chan_troi_sang_tao: 'Chân trời sáng tạo',
    ket_noi_tri_thuc: 'Kết nối tri thức với cuộc sống',
    other: 'Khác (tự nhập)',
    image_generation_error: 'Tạo ảnh thất bại',
    [Subject.MATH]: 'Toán học',
    [Subject.LITERATURE]: 'Ngữ văn',
    [Subject.PHYSICS]: 'Vật lý',
    [Subject.CHEMISTRY]: 'Hóa học',
    [Subject.BIOLOGY]: 'Sinh học',
    [Subject.HISTORY]: 'Lịch sử',
    [Subject.GEOGRAPHY]: 'Địa lý',
    [Subject.ENGLISH]: 'Tiếng Anh',
    [Subject.TECHNOLOGY]: 'Công nghệ',
    [Subject.CIVIC_EDUCATION]: 'Giáo dục công dân',
    [Subject.INFORMATICS]: 'Tin học',
    [Subject.NATURAL_SCIENCES]: 'Khoa học Tự nhiên',
    [LibraryItemType.SUMMARY]: 'Tóm tắt',
    [LibraryItemType.EXAM]: 'Đề thi',
    [LibraryItemType.REVIEW_EXERCISES]: 'Bài tập ôn',
    [LibraryItemType.SIMILAR_EXERCISES]: 'Bài tập tương tự',
  },
  [Language.ZH]: {
    slogan: '开启知识，塑造未来。',
    im_a: '我是...',
    student: '学生',
    teacher: '老师',
    select_goal: '选择你的目标',
    good_student: '好学生',
    excellent_student: '优秀学生',
    outstanding_student: '杰出学生',
    summarize: '总结',
    summarizer: '摘要器',
    exam_generator: '试卷生成器',
    ai_assistant: 'AI 助手',
    translator: '翻译器',
    slide_generator: '幻灯片生成器',
    learning_path: '学习路径',
    question_analysis: '问题分析',
    upload_file: '上传文件',
    file_placeholder: '上传文件（PDF, 图像, 音频, 视频）',
    choose_file: '选择文件',
    no_file_chosen: '未选择文件',
    generating: '生成中...',
    summary_placeholder: '您生成的摘要、思维导图和抽认卡将显示在此处。',
    mind_map: '思维导图',
    flashcards: '抽认卡',
    source_language: '源语言',
    target_language: '目标语言',
    source_text_placeholder: '输入要翻译的文本...',
    copy_text: '复制',
    copied: '已复制！',
    copy_as_text: '复制为文本',
    copy_for_word: '为 Word 复制',
    converting: '转换中...',
    swap_languages: '交换语言',
    translate_button: '翻译',
    presentation_topic: '演示主题',
    topic_placeholder: '例如，“人工智能的历史”',
    upload_template: '上传模板（可选）',
    generate_slides: '生成幻灯片',
    slide_placeholder: '您生成的幻灯片内容将显示在此处。',
    grade: '年级',
    subject: '学科',
    generate_plan: '生成计划',
    completed: '已完成',
    current_lesson: '当前课程',
    locked: '已锁定',
    plan_placeholder: '生成学习计划以开始。',
    lesson_placeholder: '选择一节课查看其内容。',
    mark_complete: '标记为完成并继续',
    exam_topic: '考试主题',
    multiple_choice: '多项选择',
    essay: '论述题',
    generate_exam: '生成试卷',
    exam_placeholder: '您生成的试题将显示在此处。',
    send_message: '发送',
    teacher_chatbot_greeting: '你好！作为您的创意AI助手，我在这里帮助您为课程集思广益。今天您在想些什么？',
    teacher_chatbot_placeholder: '今天我能如何帮助您进行课程规划或提供创意？',
    attach_file: '附加文件',
    file_attached: '已附加文件:',
    remove_file: '删除文件',
    start_recording: '开始录音',
    stop_recording: '停止录音',
    voice_unsupported: '您的浏览器不支持语音输入。',
    select_dialect: '选择方言',
    north: '北',
    central: '中',
    south: '南',
    textbook: '教科书',
    upload_matrix: '上传矩阵',
    manual_textbook_placeholder: '输入教科书名称...',
    question_analysis_title: '类似练习生成器',
    generate_similar_exercises: '生成类似练习',
    upload_question_file: '上传问题文件（图片、PDF）',
    similar_exercises_placeholder: '您生成的类似练习将显示在此处。',
    analysis_of_original_question: '原始问题分析',
    similar_practice_exercises: '类似练习题',
    read_aloud: '朗读',
    exam_duration: '考试时间（分钟）',
    num_multiple_choice: '选择题总数',
    num_essay: '按难度分列的论述题',
    difficulty_level: '难度级别',
    recognition: '认识',
    comprehension: '理解',
    application: '应用',
    mc_difficulty_breakdown: '按难度分列的选择题',
    mc_sum_error: '选择题各难度数量总和必须等于总数。',
    review_topic: '复习主题',
    generate_review_exercises: '生成练习',
    review_placeholder: '您生成的复习练习将显示在此处。',
    go_home: '返回首页',
    library: '图书馆',
    documents: '文件',
    save_to_library: '保存到图书馆',
    save_to_documents: '保存到文件',
    saved: '已保存!',
    library_empty: '你的图书馆是空的。保存生成的内容以在此处查看。',
    documents_empty: '您没有已保存的文档。保存生成的内容以在此处查看。',
    delete: '删除',
    view: '查看',
    close: '关闭',
    confirm_delete_title: '确认删除',
    confirm_delete_message: '你确定要删除这个项目吗？',
    storage_full: '存储已满。请删除一些项目以保存新内容。',
    storage_usage: '存储使用情况',
    item_name_placeholder: '为此项目输入名称...',
    save: '保存',
    zoom_in: '放大',
    zoom_out: '缩小',
    reset_zoom: '重置缩放',
    specialized_review: '专题复习',
    numbers: '数与代数',
    geometry: '几何',
    both: '两者皆是',
    sub_subjects: '子学科',
    none: '无',
    canh_dieu: 'Cánh diều',
    chan_troi_sang_tao: 'Chân trời sáng tạo',
    ket_noi_tri_thuc: 'Kết nối tri thức विद cuộc sống',
    other: '其他（手动输入）',
    image_generation_error: '图片生成失败',
    [Subject.MATH]: '数学',
    [Subject.LITERATURE]: '文学',
    [Subject.PHYSICS]: '物理',
    [Subject.CHEMISTRY]: '化学',
    [Subject.BIOLOGY]: '生物学',
    [Subject.HISTORY]: '历史',
    [Subject.GEOGRAPHY]: '地理',
    [Subject.ENGLISH]: '英语',
    [Subject.TECHNOLOGY]: '技术',
    [Subject.CIVIC_EDUCATION]: '公民教育',
    [Subject.INFORMATICS]: '信息学',
    [Subject.NATURAL_SCIENCES]: '自然科学',
    [LibraryItemType.SUMMARY]: '摘要',
    [LibraryItemType.EXAM]: '考试',
    [LibraryItemType.REVIEW_EXERCISES]: '复习练习',
    [LibraryItemType.SIMILAR_EXERCISES]: '类似练习',
  },
  [Language.FR]: {
    slogan: 'Débloquer la connaissance, façonner l\'avenir.',
    im_a: 'Je suis...',
    student: 'Étudiant(e)',
    teacher: 'Enseignant(e)',
    select_goal: 'Sélectionnez votre objectif',
    good_student: 'Bon Élève',
    excellent_student: 'Excellent Élève',
    outstanding_student: 'Élève Exceptionnel',
    summarize: 'Résumer',
    summarizer: 'Résumeur',
    exam_generator: 'Générateur d\'examen',
    ai_assistant: 'Assistant IA',
    translator: 'Traducteur',
    slide_generator: 'Générateur de diapositives',
    learning_path: 'Parcours d\'apprentissage',
    question_analysis: 'Analyse de question',
    upload_file: 'Télécharger un fichier',
    file_placeholder: 'Télécharger un fichier (PDF, image, audio, vidéo)',
    choose_file: 'Choisir un fichier',
    no_file_chosen: 'Aucun fichier choisi',
    generating: 'Génération...',
    summary_placeholder: 'Votre résumé, votre carte mentale et vos flashcards générés apparaîtront ici.',
    mind_map: 'Carte Mentale',
    flashcards: 'Flashcards',
    source_language: 'Langue source',
    target_language: 'Langue cible',
    source_text_placeholder: 'Saisissez le texte à traduire...',
    copy_text: 'Copier',
    copied: 'Copié !',
    copy_as_text: 'Copier en texte',
    copy_for_word: 'Copier pour Word',
    converting: 'Conversion...',
    swap_languages: 'Inverser les langues',
    translate_button: 'Traduire',
    presentation_topic: 'Sujet de la présentation',
    topic_placeholder: 'par exemple, "L\'histoire de l\'IA"',
    upload_template: 'Télécharger un modèle (facultatif)',
    generate_slides: 'Générer les diapositives',
    slide_placeholder: 'Le contenu de votre diapositive générée apparaîtra ici.',
    grade: 'Classe',
    subject: 'Matière',
    generate_plan: 'Générer un plan',
    completed: 'Terminé',
    current_lesson: 'Leçon actuelle',
    locked: 'Verrouillé',
    plan_placeholder: 'Générez un plan d\'apprentissage pour commencer.',
    lesson_placeholder: 'Sélectionnez une leçon pour voir son contenu.',
    mark_complete: 'Marquer comme terminé et suivant',
    exam_topic: 'Sujet de l\'examen',
    multiple_choice: 'Choix multiple',
    essay: 'Dissertation',
    generate_exam: 'Générer l\'examen',
    exam_placeholder: 'Vos questions d\'examen générées apparaîtront ici.',
    send_message: 'Envoyer',
    teacher_chatbot_greeting: 'Bonjour ! En tant qu\'assistant IA créatif, je suis là pour vous aider à trouver des idées pour vos leçons. À quoi pensez-vous aujourd\'hui ?',
    teacher_chatbot_placeholder: 'Comment puis-je vous aider aujourd\'hui avec la planification de vos leçons ou vos idées créatives ?',
    attach_file: 'Joindre un fichier',
    file_attached: 'Fichier joint:',
    remove_file: 'Supprimer le fichier',
    start_recording: 'Commencer l\'enregistrement',
    stop_recording: 'Arrêter l\'enregistrement',
    voice_unsupported: 'La saisie vocale n\'est pas prise en charge par votre navigateur.',
    select_dialect: 'Sélectionner un dialecte',
    north: 'Nord',
    central: 'Centre',
    south: 'Sud',
    textbook: 'Manuel scolaire',
    upload_matrix: 'Télécharger la matrice',
    manual_textbook_placeholder: 'Entrez le nom du manuel...',
    question_analysis_title: 'Générateur d\'Exercices Similaires',
    generate_similar_exercises: 'Générer des exercices similaires',
    upload_question_file: 'Télécharger un fichier de question (image, PDF)',
    similar_exercises_placeholder: 'Vos exercices similaires générés apparaîtront ici.',
    analysis_of_original_question: 'Analyse de la question originale',
    similar_practice_exercises: 'Exercices similaires',
    read_aloud: 'Lire à voix haute',
    exam_duration: 'Durée de l\'examen (minutes)',
    num_multiple_choice: 'Total QCM',
    num_essay: 'Dissertations par difficulté',
    difficulty_level: 'Niveau de difficulté',
    recognition: 'Reconnaissance',
    comprehension: 'Compréhension',
    application: 'Application',
    mc_difficulty_breakdown: 'QCM par difficulté',
    mc_sum_error: 'La somme des QCM doit correspondre au total.',
    review_topic: 'Sujet de révision',
    generate_review_exercises: 'Générer les exercices',
    review_placeholder: 'Vos exercices de révision générés apparaîtront ici.',
    go_home: 'Retour à l\'accueil',
    library: 'Bibliothèque',
    documents: 'Documents',
    save_to_library: 'Sauvegarder dans la Bibliothèque',
    save_to_documents: 'Sauvegarder dans les Documents',
    saved: 'Sauvegardé !',
    library_empty: 'Votre bibliothèque est vide. Enregistrez le contenu généré pour le voir ici.',
    documents_empty: 'Vous n\'avez aucun document enregistré. Enregistrez le contenu généré pour le voir ici.',
    delete: 'Supprimer',
    view: 'Voir',
    close: 'Fermer',
    confirm_delete_title: 'Confirmer la suppression',
    confirm_delete_message: 'Êtes-vous sûr de vouloir supprimer cet élément ?',
    storage_full: 'Le stockage est plein. Veuillez supprimer certains éléments pour enregistrer du nouveau contenu.',
    storage_usage: 'Utilisation du stockage',
    item_name_placeholder: 'Entrez un nom pour cet élément...',
    save: 'Sauvegarder',
    zoom_in: 'Zoom avant',
    zoom_out: 'Zoom arrière',
    reset_zoom: 'Réinitialiser le zoom',
    specialized_review: 'Révision Spécialisée',
    numbers: 'Nombres et Algèbre',
    geometry: 'Géométrie',
    both: 'Les deux',
    sub_subjects: 'Sous-matières',
    none: 'Aucun',
    canh_dieu: 'Cánh diều',
    chan_troi_sang_tao: 'Chân trời sáng tạo',
    ket_noi_tri_thuc: 'Kết nối tri thức avec cuộc sống',
    other: 'Autre (saisie manuelle)',
    image_generation_error: 'Échec de la génération d\'image',
    [Subject.MATH]: 'Mathématiques',
    [Subject.LITERATURE]: 'Littérature',
    [Subject.PHYSICS]: 'Physique',
    [Subject.CHEMISTRY]: 'Chimie',
    [Subject.BIOLOGY]: 'Biologie',
    [Subject.HISTORY]: 'Histoire',
    [Subject.GEOGRAPHY]: 'Géographie',
    [Subject.ENGLISH]: 'Anglais',
    [Subject.TECHNOLOGY]: 'Technologie',
    [Subject.CIVIC_EDUCATION]: 'Éducation Civique',
    [Subject.INFORMATICS]: 'Informatique',
    [Subject.NATURAL_SCIENCES]: 'Sciences Naturelles',
    [LibraryItemType.SUMMARY]: 'Résumé',
    [LibraryItemType.EXAM]: 'Examen',
    [LibraryItemType.REVIEW_EXERCISES]: 'Exercices de révision',
    [LibraryItemType.SIMILAR_EXERCISES]: 'Exercices similaires',
  }
};
